server:
  port: 8081

mybatis:
  type-aliases-package: yygh.parent.dandp.entity
  mapper-locations: classpath:mapper/*.xml
  configuration-properties: classpath:mybatis/mybatis-config.xml


# 打印sql
logging:
  level:
    yygh.parent.dandp.mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dandp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 600000
      # 连接池名字
      pool-name: DateSourceHikariCP
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      max-lifetime: 1800000
      connection-test-query: SELECT 1


penint:
  resourcePath:
    image: file:D:/software/image/
    uploadAvatar: D:/software/image/avatar
    AvatarUrl: /image/avatar
#    image: file:/Users/penint/Documents/image/
#    uploadAvatar: /Users/penint/Documents/image/avatar
#    AvatarUrl: /image/avatar
